In [1]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import numpy as np

In [2]:
path='C:/Users/MALIK/Documents/ProgramaDelfin/incidenciaMunicipal2015_sin99.csv'
df = pd.read_csv(path,encoding='latin',low_memory=False)
df.head()

Unnamed: 0  CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  \
0           0        1        1        6        15           16      4   
1           1        1        1        6        15           17      9   
2           2        1        1        6        15           18      4   
3           3        1        1        6        15           19      0   
4           4        1        1        6        15           20     34   

   FEBRERO  MARZO  ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  \
0        3      0      7     4      6      4       3           4        1   
1       10     10     11    11      6     10      18           8        3   
2        1      5      3     0      1      1       4           2        5   
3        0      0      0     1      0      0       0           0        0   
4       32     46     44    49     34     49      56          34       24   

   NOVIEMBRE  DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          4          7             43                      2  
1         14         14            115                      2  
2          6          4             32                      2  
3          1          0              2                      2  
4         49         32            449                      2

In [3]:
df.drop('Unnamed: 0', 1, inplace=True)

In [4]:
df.head()

CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  FEBRERO  MARZO  \
0        1        1        6        15           16      4        3      0   
1        1        1        6        15           17      9       10     10   
2        1        1        6        15           18      4        1      5   
3        1        1        6        15           19      0        0      0   
4        1        1        6        15           20     34       32     46   

   ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  NOVIEMBRE  \
0      7     4      6      4       3           4        1          4   
1     11    11      6     10      18           8        3         14   
2      3     0      1      1       4           2        5          6   
3      0     1      0      0       0           0        0          1   
4     44    49     34     49      56          34       24         49   

   DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          7             43                      2  
1         14            115                      2  
2          4             32                      2  
3          0              2                      2  
4         32            449                      2

In [5]:
df1 = df[['CVE_ENT','CVE_MUN','VIVIENDA_ENDUTIH_2015']]


In [6]:
X = df[['CVE_ENT','CVE_MUN','VIVIENDA_ENDUTIH_2015']].values

In [7]:
X.shape

(53658, 3)

In [8]:
df1.shape

(53658, 3)

In [9]:
y = np.array(df[df.columns[-2]])
y.shape


(53658,)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [11]:
X_train

array([[32, 31,  0],
       [19,  9,  1],
       [ 5, 14,  2],
       ...,
       [24, 47,  0],
       [ 2,  3,  2],
       [13, 48,  3]], dtype=int64)

In [12]:
X_train.shape

(37560, 3)

In [13]:
y_train

array([ 0,  0, 17, ...,  0,  2, 32], dtype=int64)

In [14]:
y_train.shape

(37560,)

In [15]:
X_test

array([[32, 56,  0],
       [ 9, 13,  0],
       [ 6,  4,  2],
       ...,
       [ 2,  5,  2],
       [ 7, 89,  3],
       [15, 28,  0]], dtype=int64)

In [16]:
X_test.shape

(16098, 3)

In [17]:
y_test

array([123, 158,   0, ...,   0,  56,  31], dtype=int64)

In [18]:
y_test.shape

(16098,)

In [19]:
X_train.shape[1]

3

In [20]:
from sklearn import svm
clf = svm.SVR()

In [21]:
clf.fit(X_train, y_train) 

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [22]:
predictions = clf.predict(X_test)


In [23]:
predictions = (predictions*10).astype('int')


In [24]:
predictions.max()

53

In [25]:
predictions.min()

0

In [26]:
predictions

array([0, 1, 0, ..., 1, 2, 0])

In [261]:
np.unique(predictions)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 15, 18, 19, 20,
       24, 28, 29, 30, 31, 35, 44, 48, 53])

In [27]:
y.max()


11929

In [28]:
y.min()

0

In [29]:
predictions = (predictions).T
predictions.shape

(16098,)

In [30]:
y_test.shape

(16098,)

In [31]:
hits = 0

for i in range(1,len(predictions)):
    if(predictions[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/predictions.shape[0])*100), '%')

performance: 32 %


## Lasso

In [32]:
path='C:/Users/MALIK/Documents/ProgramaDelfin/incidenciaMunicipal2015_sin99.csv'
df2 = pd.read_csv(path,encoding='latin',low_memory=False)
df2.head()

Unnamed: 0  CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  \
0           0        1        1        6        15           16      4   
1           1        1        1        6        15           17      9   
2           2        1        1        6        15           18      4   
3           3        1        1        6        15           19      0   
4           4        1        1        6        15           20     34   

   FEBRERO  MARZO  ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  \
0        3      0      7     4      6      4       3           4        1   
1       10     10     11    11      6     10      18           8        3   
2        1      5      3     0      1      1       4           2        5   
3        0      0      0     1      0      0       0           0        0   
4       32     46     44    49     34     49      56          34       24   

   NOVIEMBRE  DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          4          7             43                      2  
1         14         14            115                      2  
2          6          4             32                      2  
3          1          0              2                      2  
4         49         32            449                      2

In [33]:
df2.drop('Unnamed: 0', 1, inplace=True)
df2.head()

CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  FEBRERO  MARZO  \
0        1        1        6        15           16      4        3      0   
1        1        1        6        15           17      9       10     10   
2        1        1        6        15           18      4        1      5   
3        1        1        6        15           19      0        0      0   
4        1        1        6        15           20     34       32     46   

   ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  NOVIEMBRE  \
0      7     4      6      4       3           4        1          4   
1     11    11      6     10      18           8        3         14   
2      3     0      1      1       4           2        5          6   
3      0     1      0      0       0           0        0          1   
4     44    49     34     49      56          34       24         49   

   DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          7             43                      2  
1         14            115                      2  
2          4             32                      2  
3          0              2                      2  
4         32            449                      2

In [34]:
df3 = df2[['CVE_ENT','CVE_MUN','VIVIENDA_ENDUTIH_2015']]


In [35]:
X = df2[['CVE_ENT','CVE_MUN','VIVIENDA_ENDUTIH_2015']].values

In [36]:
X.shape

(53658, 3)

In [37]:
df3.shape

(53658, 3)

In [38]:
y = np.array(df2[df2.columns[-2]])
y.shape

(53658,)

In [98]:
y

array([ 43, 115,  32, ...,   0,   1,  47], dtype=int64)

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [79]:
X_train

array([[13, 46,  3],
       [18, 14,  1],
       [ 7, 74,  3],
       ...,
       [24, 47,  0],
       [ 2,  3,  2],
       [13, 48,  3]], dtype=int64)

In [80]:
X_train.shape

(35950, 3)

In [81]:
y_train

array([ 0,  0, 11, ...,  0,  2, 32], dtype=int64)

In [82]:
y_train.shape

(35950,)

In [83]:
X_test

array([[32, 56,  0],
       [ 9, 13,  0],
       [ 6,  4,  2],
       ...,
       [15, 42,  3],
       [28,  2,  1],
       [13, 41,  3]], dtype=int64)

In [84]:
X_test.shape

(17708, 3)

In [85]:
X_train.shape[1]

3

In [86]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha = 1.0, normalize=True)

In [87]:
reg.fit(X_train, y_train)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [88]:
predictions2 = clf.predict(X_test)


In [89]:
predictions2 = (predictions2*10).astype('int')


In [90]:
predictions2.max()

53

In [91]:
predictions2.min()

0

In [260]:
np.unique(predictions2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 15, 18, 19, 20,
       24, 28, 29, 30, 31, 35, 44, 48, 53])

In [92]:
predictions2

array([0, 1, 0, ..., 1, 1, 1])

In [93]:
y.max()

11929

In [94]:
y.min()

0

In [95]:
predictions2 = (predictions2).T
predictions2.shape

(17708,)

In [96]:
y_test.shape

(17708,)

In [77]:
hits = 0

for i in range(1,len(predictions2)):
    if(predictions2[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/predictions2.shape[0])*100), '%')

performance: 32 %


## Random Forest

In [99]:
path='C:/Users/MALIK/Documents/ProgramaDelfin/incidenciaMunicipal2015_sin99.csv'
df4 = pd.read_csv(path,encoding='latin',low_memory=False)
df4.head()

Unnamed: 0  CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  \
0           0        1        1        6        15           16      4   
1           1        1        1        6        15           17      9   
2           2        1        1        6        15           18      4   
3           3        1        1        6        15           19      0   
4           4        1        1        6        15           20     34   

   FEBRERO  MARZO  ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  \
0        3      0      7     4      6      4       3           4        1   
1       10     10     11    11      6     10      18           8        3   
2        1      5      3     0      1      1       4           2        5   
3        0      0      0     1      0      0       0           0        0   
4       32     46     44    49     34     49      56          34       24   

   NOVIEMBRE  DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          4          7             43                      2  
1         14         14            115                      2  
2          6          4             32                      2  
3          1          0              2                      2  
4         49         32            449                      2

In [100]:
df4.drop('Unnamed: 0', 1, inplace=True)
df4.head()

CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  FEBRERO  MARZO  \
0        1        1        6        15           16      4        3      0   
1        1        1        6        15           17      9       10     10   
2        1        1        6        15           18      4        1      5   
3        1        1        6        15           19      0        0      0   
4        1        1        6        15           20     34       32     46   

   ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  NOVIEMBRE  \
0      7     4      6      4       3           4        1          4   
1     11    11      6     10      18           8        3         14   
2      3     0      1      1       4           2        5          6   
3      0     1      0      0       0           0        0          1   
4     44    49     34     49      56          34       24         49   

   DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          7             43                      2  
1         14            115                      2  
2          4             32                      2  
3          0              2                      2  
4         32            449                      2

In [101]:
X = df4[['CVE_ENT','CVE_MUN','VIVIENDA_ENDUTIH_2015']].values

In [102]:
X.shape

(53658, 3)

In [103]:
df4.shape

(53658, 19)

In [104]:
y = np.array(df4[df4.columns[-2]])
y.shape

(53658,)

In [105]:
y

array([ 43, 115,  32, ...,   0,   1,  47], dtype=int64)

In [320]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [321]:
X_train

array([[ 21, 140,   3],
       [  4,  11,   2],
       [ 13,  62,   3],
       ...,
       [ 24,  47,   0],
       [  2,   3,   2],
       [ 13,  48,   3]], dtype=int64)

In [322]:
X_train.shape

(42926, 3)

In [323]:
y_train

array([ 0,  5,  0, ...,  0,  2, 32], dtype=int64)

In [324]:
y_train.shape

(42926,)

In [325]:
X_test

array([[ 32,  56,   0],
       [  9,  13,   0],
       [  6,   4,   2],
       ...,
       [ 30, 108,   3],
       [ 30, 102,   3],
       [ 10,  39,   3]], dtype=int64)

In [326]:
X_test.shape

(10732, 3)

In [327]:
X_train.shape[1]

3

In [354]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10,random_state=30)

In [355]:
clf=clf.fit(X_train, y_train)

In [356]:
predictions3 = clf.predict(X_test)


In [357]:
predictions3 = (predictions3*10).astype('int')


In [358]:
predictions3.max()

0

In [359]:
np.unique(predictions3)

array([0])

In [360]:
predictions3.min()

0

In [361]:
predictions3

array([0, 0, 0, ..., 0, 0, 0])

In [362]:
y.max()

11929

In [363]:
y.min()

0

In [364]:
predictions3 = (predictions3).T
predictions3.shape

(10732,)

In [365]:
y_test.shape

(10732,)

In [366]:
hits = 0

for i in range(1,len(predictions3)):
    if(predictions3[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/predictions3.shape[0])*100), '%')

performance: 67 %
